services:
  cogigo_db:
    container_name: cogigo_db
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - "cogigo_data:/var/lib/postgresql/18/docker"
    ports:
      - "5432:5432"

volumes:
  cogigo_data: {}
