services:
  cogigo_db:
    container_name: cogigo_db
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - 'cogigo_data:/var/lib/postgresql/18/docker'
    networks:
      - proxy
  adminer:
    container_name: adminer
    image: adminer:latest
    networks:
      - proxy
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.entrypoints=http"
      - "traefik.http.routers.adminer.rule=Host(`adminer.cogito-ntnu.no`)"
      - "traefik.http.routers.adminer.service=adminer"
      - "traefik.http.middlewares.adminer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adminer.middlewares=adminer-https-redirect"
      - "traefik.http.routers.adminer-secure.entrypoints=https"
      - "traefik.http.routers.adminer-secure.rule=Host(`adminer.cogito-ntnu.no`)"
      - "traefik.http.routers.adminer-secure.tls=true"
      - "traefik.http.routers.adminer-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.adminer-secure.service=adminer"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  cogito_backend:
    container_name: cogito_backend
    image: ghcr.io/cogitontnu/cogi-go:latest
    entrypoint: ["/bin/sh","-lc"]
    command: "./main"
    environment:
      ENVIRONMENT: "PRODUCTION"
      SQL_HOST: cogigo_db
      SQL_PORT: 5432
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_DATABASE: postgres
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=http"
      - "traefik.http.routers.backend.rule=Host(`backend.cogito-ntnu.no`)"
      - "traefik.http.routers.backend.service=cogito"
      - "traefik.http.middlewares.backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.backend.middlewares=backend-https-redirect"
      - "traefik.http.routers.backend-secure.entrypoints=https"
      - "traefik.http.routers.backend-secure.rule=Host(`backend.cogito-ntnu.no`)"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.routers.backend-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.backend-secure.service=cogito"
      - "traefik.http.services.cogito.loadbalancer.server.port=8080"
    depends_on:
      cogigo_db:
        condition: service_healthy

volumes:
  cogigo_data: {}

networks:
  proxy:
    external: true